# -*- coding: utf-8 -*-
"""tf_std_server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_esEslXB1WuYVeGVnRDQY6pRDJhmz2X9
"""

"""Run a standard tensorflow server."""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf


def main(unused_argv):
  # Contrib ops are lazily loaded. So we touch one contrib module to load them
  # immediately.
  to_import_contrib_ops = tf.contrib.resampler

  # Load you custom ops here before starting the standard TensorFlow server.

  # Start and join the standard TensorFlow server.
  tf.contrib.distribute.run_standard_tensorflow_server().join()


if __name__ == "__main__":
  tf.app.run()